<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="TJ-" failures="2" tests="2" name="Test(failed)" time="0.092" errors="0" timestamp="2024-10-26T08:39:11 IST">
  <testcase classname="Demo.SecondTestCase" name="TestMethod_3" time="0.019">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at Demo.SecondTestCase.TestMethod_3(SecondTestCase.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- TestMethod_3 -->
  <testcase classname="Demo.SecondTestCase" name="TestMethod_2" time="0.013">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at Demo.SecondTestCase.TestMethod_2(SecondTestCase.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- TestMethod_2 -->
  <testcase classname="Demo.SecondTestCase" name="TestMethod_1" time="0.0">
    <ignored/>
  </testcase> <!-- TestMethod_1 -->
</testsuite> <!-- Test(failed) -->
